name: CI

on:
  push: 
    branches: [ main ]
    
  workflow_dispatch: 
  
jobs:
  build: 
    runs-on: ubuntu-latest,
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Nodejs
        uses: actions/setup-node@v3 
        with: 
          node-version: 16,
          cache: 'npm'
        
      - name: Install Dependencies
        run: npm i
        
      - name: Build
        run: npm run build
        
      - uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          source: "., !node_modules"
          target: teste
        
        
